spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
